apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: kro.fling.vsphere.vmware.com.0.0.0
spec:
  refName: kro.fling.vsphere.vmware.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - helmTemplate:
          path: upstream
      - ytt:
          paths:
          - '-'
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: kro.fling.vsphere.vmware.com
spec:
  displayName: kro
  longDescription: kro.fling.vsphere.vmware.com
  shortDescription: kro.fling.vsphere.vmware.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: kro
spec:
  packageRef:
    refName: kro.fling.vsphere.vmware.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kro-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
